name: lp-mini-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pillow
  - scikit-learn
  - openpyxl
  - pip:
    - torch
    - torchvision
    - torchaudio
    - mlflow
